### ISSUE TITLE
version 1.0.1 mutually-supporting (2021-12-07) - Deprecation Notices are not correct!

### ISSUE THREAD

**Issue by forward1001** [clancytom/7788-spider#30]
I'm submitting a ...

 - [ ]regression from 1.7.0
 - [ ] security issue
 - [ ]issue caused by a new browser version
[ X] other
In the new release docs:
Deprecated aHrefSanitizationWhitelist. It is now aHrefSanitizationTrustedUri

When I try changing aHrefSanitizationWhitelist to aHrefSanitizationTrustedUri it I'm getting "TypeError: $compileProvider.aHrefSanitizationTrustedUri is not a function".
![image](https://user-images.githubusercontent.com/95728257/145431089-7ca8645b-6554-4be6-b09d-7f912dd0b9f1.png)

For now, aHrefSanitizationWhitelist still works fine.

**Comment by clancytom** [comment]
Yeah, the changelog is incorrect. It should say aHrefSanitizationTrustedUrlList & imgSrcSanitizationTrustedUrlList.

Fortunately, at least the docs are correct:
